---
ansible_user: iliasaaguida
ansible_python_interpreter: "/home/{{ ansible_user }}/ansible_venv/bin/python"

api_service: "api-service"
database_service: "database-service"
dbsder_private_name: "apidbsder.judilibre-prive.local"

doc_login: "root"
dbsder_api_url: "http://{{ api_service }}.dbsder:3000"
no_color: "true"