image: docker:20.10.22
services:
  - docker:20.10.22-dind

stages:
  - test
  - build
  - deploy

test:
  stage: test
  services:
  - docker:20.10.22
  variables:
    HTTP_PROXY: $HTTP_PROXY
    HTTPS_PROXY: $HTTPS_PROXY
    DBSDER_API_LABEL_API_KEY: $DBSDER_API_LABEL_API_KEY
    DBSDER_API_NORMALIZATION_API_KEY: $DBSDER_API_NORMALIZATION_API_KEY
    DBSDER_API_OPENSDER_API_KEY: $DBSDER_API_OPENSDER_API_KEY
    DBSDER_API_OPS_API_KEY: $DBSDER_API_OPS_API_KEY
    DBSDER_API_DOC_LOGIN: $DBSDER_API_DOC_LOGIN
    DBSDER_API_DOC_PASSWORD: $DBSDER_API_DOC_PASSWORD
    DBSDER_API_MONGO_DB_URL: $DBSDER_API_MONGO_DB_URL
  script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build 
        --build-arg http_proxy=$HTTP_PROXY
        --build-arg https_proxy=$HTTPS_PROXY
        --target test
        -t dbsder-api .
    #- docker run -e HTTP_PROXY=$HTTP_PROXY -e HTTPS_PROXY=$HTTPS_PROXY dbsder-api npm audit
    - docker run -e HTTP_PROXY=$HTTP_PROXY -e HTTPS_PROXY=$HTTPS_PROXY dbsder-api npm run format
    - docker run -e HTTP_PROXY=$HTTP_PROXY -e HTTPS_PROXY=$HTTPS_PROXY dbsder-api npm run lint
    - docker run -e HTTP_PROXY=$HTTP_PROXY -e HTTPS_PROXY=$HTTPS_PROXY dbsder-api npm test
    - echo 'ok'
  only:
    - master
    - re7
    - dev
  tags:
    - docker

build_api:
  stage: build
  variables:
    HTTP_PROXY: $HTTP_PROXY
    HTTPS_PROXY: $HTTPS_PROXY
  script: 
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build
        --build-arg http_proxy=$HTTP_PROXY
        --build-arg https_proxy=$HTTPS_PROXY
        --target api
        -t $CI_REGISTRY/cour-de-cassation/dbsder-api:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-api .
    - docker push $CI_REGISTRY/cour-de-cassation/dbsder-api:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-api
  only:
    - master
    - re7
    - dev
  tags:
    - docker

deploy_api:
  stage: deploy
  variables:
    DBSDER_API_LABEL_API_KEY: $DBSDER_API_LABEL_API_KEY
    DBSDER_API_NORMALIZATION_API_KEY: $DBSDER_API_NORMALIZATION_API_KEY
    DBSDER_API_OPENSDER_API_KEY: $DBSDER_API_OPENSDER_API_KEY
    DBSDER_API_OPS_API_KEY: $DBSDER_API_OPS_API_KEY
    DBSDER_API_DOC_LOGIN: $DBSDER_API_DOC_LOGIN
    DBSDER_API_DOC_PASSWORD: $DBSDER_API_DOC_PASSWORD
    DBSDER_API_MONGO_DB_URL: $DBSDER_API_MONGO_DB_URL
    DOLLAR: $$
  script:
    - envsubst < .deploys/deploy_namespace.yaml | kubectl --kubeconfig=/home/gitlab-runner/.kube/$CI_COMMIT_BRANCH apply -f -
    - envsubst < .deploys/deploy_api.yaml | kubectl --kubeconfig=/home/gitlab-runner/.kube/$CI_COMMIT_BRANCH apply -f -
    - envsubst < .deploys/deploy_bucket.yaml | kubectl --kubeconfig=/home/gitlab-runner/.kube/$CI_COMMIT_BRANCH apply -f -
    - envsubst < .deploys/deploy_database.yaml | kubectl --kubeconfig=/home/gitlab-runner/.kube/$CI_COMMIT_BRANCH apply -f -
    - envsubst < .deploys/deploy_ingress.yaml | kubectl --kubeconfig=/home/gitlab-runner/.kube/$CI_COMMIT_BRANCH apply -f -
  only:
    - master
    - re7
    - dev
  tags:
    - shell
  dependencies:
    - build_api