image: docker:20.10.22
services:
  - docker:20.10.22-dind

variables:
  dev: dev
  re7: preprod
  master: prod
  api_docker_image: "$CI_REGISTRY/cour-de-cassation/dbsder-api:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-api"


stages:
  - test
  - build
  - deploy

test:
  stage: test
  services:
  - docker:20.10.22
  variables:
    HTTP_PROXY: $HTTP_PROXY_DEV
    HTTPS_PROXY: $HTTPS_PROXY_DEV
  script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build 
        --build-arg http_proxy=$HTTP_PROXY
        --build-arg https_proxy=$HTTPS_PROXY
        --target test
        -t dbsder-api .
    #- docker run -e HTTP_PROXY=$HTTP_PROXY -e HTTPS_PROXY=$HTTPS_PROXY dbsder-api npm audit
    - docker run -e HTTP_PROXY=$HTTP_PROXY -e HTTPS_PROXY=$HTTPS_PROXY dbsder-api npm run format
    - docker run -e HTTP_PROXY=$HTTP_PROXY -e HTTPS_PROXY=$HTTPS_PROXY dbsder-api npm run lint
    - docker run -e HTTP_PROXY=$HTTP_PROXY -e HTTPS_PROXY=$HTTPS_PROXY dbsder-api npm test
    - echo 'ok'
  only:
    - ajout_ansible
    - master
    - re7
    - dev
  tags:
    - docker

build_api:
  stage: build
  variables:
    HTTP_PROXY: $HTTP_PROXY
    HTTPS_PROXY: $HTTPS_PROXY
  script: 
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build
        --build-arg http_proxy=$HTTP_PROXY
        --build-arg https_proxy=$HTTPS_PROXY
        --target api
        -t $CI_REGISTRY/cour-de-cassation/dbsder-api:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-api .
    - docker push $CI_REGISTRY/cour-de-cassation/dbsder-api:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-api
  only:
    - ajout_ansible
    - master
    - re7
    - dev
  tags:
    - docker


deploy_api:
  stage: deploy
  image: alpine/ansible:latest
  variables:
    DOLLAR: $$
  script:
    - inventaire=$(eval "echo \$$CI_COMMIT_BRANCH")
    - mkdir /root/.ssh
    - cat $SSH_KEY > /root/.ssh/id_rsa
    - cat $KNOWN_HOSTS > /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/known_hosts
    - ansible-playbook -e dbsder_api_image=$api_docker_image -i ansible/inventory/$inventaire.yml ansible/deploy_dbsder.yml --vault-password-file=$ANSIBLE_VAULT_PASS
  rules:
    - if: $CI_COMMIT_BRANCH == "ajout_ansible" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "re7"
      when: manual
    - if: $CI_COMMIT_BRANCH == "dev"
      when: on_success

  tags:
    - docker
  dependencies:
    - build_api
