name: dbsder-api

services:
  dbsder-api:
    build:
      context: ./
      target: api-local
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/home/node
