name: dbsder-api

services:
  db:
    image: mongo:4.4
    env_file:
      - docker.env
    command: mongod --port 55433
    volumes:
      - dbsder-mongo-storage:/data/db-sder/db
    ports:
      - 55433:55433
    networks: 
      - judilibre-local

  dbsder-api:
    build:
      context: ./
      target: api-local
    env_file:
      - docker.env
    ports:
      - 3008:3008
    networks: 
      - judilibre-local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/home/node

networks:
  default:
  judilibre-local:
    name: judilibre-local

volumes:
  dbsder-mongo-storage:
    driver: local
    name: dbsder-mongo-storage


