name: dbsder-api

services:
  db:
    image: mongo:4.4
    env_file:
      - docker.env
    command: mongod --port 55433
    volumes:
      - dbsder-mongo-storage:/data/db-sder/db
    expose:
      - 55433
    ports:
      - 55433:55433

  dbsder-api:
    build:
      context: ./
      target: api-local
    env_file:
      - docker.env
    expose: 
      - 3008
    ports:
      - 3008:3000
    networks: 
      - default
      - dbsder-external-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/home/node

networks:
  default:
  dbsder-external-network:
    name: dbsder-external-network

volumes:
  dbsder-mongo-storage:
    driver: local
    name: dbsder-mongo-storage


