---
- name: Create Deployment database
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ database_app_id }}-deployment"
        namespace: "{{ dbsder_namespace }}"
        labels:
          app:
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ database_app_id }}"
        template:
          metadata:
            labels:
              app: "{{ database_app_id }}"
          spec:
            containers:
              - name: "{{ database_app_id }}"
                image: mongo:6.0.4-jammy
                ports:
                  - containerPort: 27017
                volumeMounts:
                  - name: database-volume
                    mountPath: /data/db-sder/db 
            volumes:
              - name: database-volume
                hostPath:
                  path: /data/db-sder/mongodb
...
