---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route
  namespace: dbsder
spec:
  entryPoints:
    - web

  routes:
    - match: Host(`apidbsder.judilibre-prive.local`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: api-service
          port: api


