apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: dbsder
  labels:
    app: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: $CI_REGISTRY/cour-de-cassation/dbsder-api:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-api
          ports:
            - containerPort: 3000
          env:
            - name: LABEL_API_KEY
              value: $DBSDER_API_LABEL_API_KEY
            - name: NORMALIZATION_API_KEY
              value: $DBSDER_API_NORMALIZATION_API_KEY
            - name: OPENSDER_API_KEY
              value: $DBSDER_API_OPENSDER_API_KEY
            - name: MONGO_DB_URL
              value: $DBSDER_API_MONGO_DB_URL
            - name: DOC_LOGIN
              value: $DBSDER_API_DOC_LOGIN
            - name: DOC_PASSWORD
              value: $DBSDER_API_DOC_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: dbsder
spec:
  selector:
    app: api
  ports:
    - name: api
      port: 3000
      targetPort: 3000
  type: ClusterIP
