---
- name: Creation ingress
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: ingress-route
        namespace: "{{ dbsder_namespace }}"
      spec:
        entryPoints:
          - web
        routes:
          - match: "Host(`{{ dbsder_private_name }}`) && PathPrefix(`/`)"
            kind: Rule
            services:
              - name: "{{ api_service }}"
                port: api

...
